// The RR7 node server. This process owns the HTTP port directly. No
// Fastify, no Express, no adapter in the request path (plan.md R1) --
// `createRequestListener` is React Router's own primitive for bridging a
// Fetch-standard request handler onto Node's built-in `http` server, and
// nothing else sits between the socket and the router.
//
// Request logging is off by construction: nothing here writes access logs.
// The greppable statement is `REQUEST_LOGGING` in server/http.ts, which also
// holds the Content-Security-Policy and the error path that carries no query
// context. This file is the composition root -- it is the only module that
// imports the generated bundle, and therefore the only one a test cannot
// import, which is exactly why nothing verifiable lives in it.
//
// See docs/privacy/verification.md for how an outsider checks all of it.

import { createServer } from "node:http";
import type { Socket } from "node:net";
import { createRequestListener } from "@react-router/node";

import {
  bodyForClientError,
  CONTENT_SECURITY_POLICY,
  respondWithoutQueryContext,
  withSecurityEnvelope,
} from "./http.ts";
import { sealProcessOutput, writeSealedLine } from "./silence.ts";
import { serveStaticAsset } from "./static.ts";

const PORT = Number(process.env.PORT ?? 3000);

const listener = createRequestListener({
  // Imported lazily so a build failure surfaces as a clear startup error
  // rather than a bundling concern for this file.
  //
  // The bundle is generated by `npm run build` into build/, which tsconfig
  // excludes from the typechecked tree and which RR7 emits without a
  // declaration file. There is nothing to type-check here -- the alternative
  // would be typechecking a generated bundle -- so the specifier is ignored
  // rather than the whole file being dropped from `npm run typecheck`.
  // @ts-ignore -- generated bundle, no declarations emitted by RR7
  build: () => import("../build/server/index.js"),
});

// The client build is served by this same process (see server/static.ts for
// why that is not an adapter and why a 404 stylesheet was a privacy defect).
// Assets first, React Router for everything else.
const server = createServer(
  withSecurityEnvelope((req, res) => {
    if (serveStaticAsset(req, res)) return;
    return listener(req, res);
  }),
);

// A request malformed enough that Node rejects it before a ServerResponse
// exists at all -- a bad request line, an oversized header block, an invalid
// chunked body, or a TLS ClientHello arriving where a request line was
// expected. Node's default handler answers `400 Bad Request` with no headers,
// which would be the one response in this process without a policy on it. It
// also emits nothing to stderr, and neither does this.
//
// The error is passed to `bodyForClientError`, which reads its parser CODE and
// (for a TLS record) two protocol-constant bytes, and returns one of three
// fixed constants. Nothing derived from the request reaches the socket -- see
// that function for why this is not a hole in the rule that the error is never
// inspected. Two of the three answers name a cause and a way out, because
// these are the only failures tarrow can explain: the parser rejected them
// before an address existed to protect (TASK-0014).
server.on("clientError", (err: Error, socket: Socket) => {
  if (socket.writableEnded || socket.destroyed) return;
  const body = Buffer.from(bodyForClientError(err), "utf8");
  socket.end(
    "HTTP/1.1 400 Bad Request\r\n" +
      "Content-Type: text/plain; charset=utf-8\r\n" +
      `Content-Length: ${body.length}\r\n` +
      `Content-Security-Policy: ${CONTENT_SECURITY_POLICY}\r\n` +
      "Referrer-Policy: same-origin\r\n" +
      "Cache-Control: no-store, no-cache, must-revalidate, private\r\n" +
      "X-Content-Type-Options: nosniff\r\n" +
      "X-Frame-Options: DENY\r\n" +
      "Connection: close\r\n" +
      "\r\n" +
      body.toString("utf8"),
  );
});

// A response that dies between the handler and the wire -- a socket reset
// mid-body, a write to a closed stream. Node's default is to emit an
// unhandled 'error' event, which crashes the process and prints the reason.
// Nothing is written about it here either.
server.on("request", (_req, res) => {
  res.on("error", () => respondWithoutQueryContext(res));
});

// Node's default handler for an escaped error prints the message and the full
// stack to stderr. A stack frame can carry an argument, and a driver error can
// carry query text -- so the default is a log of what was searched, arriving
// through the one path nobody writes down. These handlers replace it with a
// fixed constant.
//
// The cost is real and accepted: a crash in this process is not diagnosable
// from its output. Principle III's trade is that the control is not holding
// the data, and an error report that "usually" omits the address is a control
// an outsider cannot check. Reproduce faults against fixture data instead --
// docs/privacy/verification.md says so in the same words.
const CRASH_LINE =
  "tarrow: fatal error in the request process. No error content is printed, " +
  "by design (Constitution Principle III). Exiting.";

process.on("uncaughtException", () => {
  writeSealedLine(CRASH_LINE);
  process.exit(1);
});
process.on("unhandledRejection", () => {
  writeSealedLine(CRASH_LINE);
  process.exit(1);
});

server.listen(PORT, () => {
  // Startup line only. Never per-request, and never carries a path, query
  // string, or remote address.
  //
  // Then the process is SEALED: from here on nothing loaded into it can write
  // to stdout or stderr, including dependencies that log a request URL from
  // code nobody in this repository wrote. See server/silence.ts for the three
  // places that already did, and why closing each at its source was not
  // enough on its own.
  writeSealedLine(`tarrow app listening on :${PORT}`);
  sealProcessOutput();
});
